import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  // Static-first approach - pages will be statically generated by default
  // Client-side features like modals work fine with SSG
};

export default nextConfig;
